language: node_js
sudo: false
node_js:
  - '0.10'
before_script:
  - 'npm install -g bower'
  - 'npm install -g grunt-cli'
  - 'bower install'
  - 'export DISPLAY=:99.0'
  - 'sh -e /etc/init.d/xvfb start'
